name: "PHP-CS-Fixer"

on:
    push:
        branches:
            - "[0-9]+.[0-9]+"
            - "[0-9]+.x"

permissions:
    contents: write

jobs:
  php-style:
    uses: pimcore/workflows-collection-public/.github/workflows/reusable-php-style.yaml@main
    with:
      head_ref: ${{ github.ref_name }}
    secrets:
      PHP_CS_FIXER_GITHUB_TOKEN: ${{ secrets.PHP_CS_FIXER_GITHUB_TOKEN }}
